on: [push]

name: Build

jobs:
  build_and_test:
    name: Controller build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-deb
          version: latest
          use-tool-cache: true
      - run: apt install libdbus-1-dev pkg-config
      - run: cargo deb -- --release
      - uses: actions/upload-artifact@v3
        with:
          name: ble.deb
          path: target/debian/ble-fencer*.deb