on: [push]

name: Build

jobs:
  build_and_test:
    name: Controller build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: ⚡ Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-deb
          version: latest
          use-tool-cache: true
      - run: sudo apt install libdbus-1-dev pkg-config
      - run: cargo deb -- --release
      - uses: actions/upload-artifact@v3
        with:
          name: ble.deb
          path: target/debian/ble-fencer*.deb